<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TMDB"
           tests="4"
           failures="2"
           errors="0"
           skipped="0"
           time="2.329">
    <properties></properties>

            <testcase
                name="favoriteMovies"
                time="0.181"
                classname="testcases.AuthenticationManagement">

            <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
                <![CDATA[java.lang.AssertionError: expected [200] but found [404]
                org.testng.Assert.fail(Assert.java:111)org.testng.Assert.failNotEquals(Assert.java:1578)org.testng.Assert.assertEqualsImpl(Assert.java:150)org.testng.Assert.assertEquals(Assert.java:132)org.testng.Assert.assertEquals(Assert.java:656)org.testng.Assert.assertEquals(Assert.java:666)testcases.AuthenticationManagement.favoriteMovies(AuthenticationManagement.java:40)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1597)org.testng.TestRunner.privateRun(TestRunner.java:848)org.testng.TestRunner.run(TestRunner.java:621)org.testng.SuiteRunner.runTest(SuiteRunner.java:443)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)org.testng.SuiteRunner.run(SuiteRunner.java:336)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)org.testng.TestNG.runSuitesLocally(TestNG.java:1200)org.testng.TestNG.runSuites(TestNG.java:1114)org.testng.TestNG.run(TestNG.java:1082)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </failure>
    </testcase>
            <testcase
                name="authenticationSuccess"
                time="1.399"
                classname="testcases.AuthenticationManagement">

            <failure type="java.lang.AssertionError" message="message expected [200] but found [404]">
                <![CDATA[java.lang.AssertionError: message expected [200] but found [404]
                org.testng.Assert.fail(Assert.java:111)org.testng.Assert.failNotEquals(Assert.java:1578)org.testng.Assert.assertEqualsImpl(Assert.java:150)org.testng.Assert.assertEquals(Assert.java:132)org.testng.Assert.assertEquals(Assert.java:656)testcases.AuthenticationManagement.authenticationSuccess(AuthenticationManagement.java:21)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1597)org.testng.TestRunner.privateRun(TestRunner.java:848)org.testng.TestRunner.run(TestRunner.java:621)org.testng.SuiteRunner.runTest(SuiteRunner.java:443)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)org.testng.SuiteRunner.run(SuiteRunner.java:336)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)org.testng.TestNG.runSuitesLocally(TestNG.java:1200)org.testng.TestNG.runSuites(TestNG.java:1114)org.testng.TestNG.run(TestNG.java:1082)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </failure>
    </testcase>


            <testcase
                name="lists"
                time="0.546"
                classname="testcases.AuthenticationManagement">
            </testcase>
            <testcase
                name="ratedMovies"
                time="0.203"
                classname="testcases.AuthenticationManagement">
            </testcase>
</testsuite>
